version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: cd ./Nodinite.Serilog.Msmq
  - nuget restore
build_script:
after_build:
  # For once the build has completed
artifacts:
 - path: '\Nodinite.Serilog.MSMQ\Nodinite.Serilog.MSMQ\bin\Debug\'
   name: MsmqSink
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off